language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "11"

os:
  - linux
  - windows

script:
  - npm run lint && npm run coveralls && npm run typescript

notifications:
  email:
    on_success: never
    on_failure: always
